### ISSUE TITLE
Turning off the heating

### ISSUE THREAD

**Issue by GiridharKarnik** [orlopau/ember-mug#4]
## Description

Looks like the following is not true

```
Sending 0000 turns off the heater
```

Do you guys have any idea on how (if at all possible) to turn off the heater?

**Comment by avojak** [comment]
I can confirm that it does work sending `0x00 0x00` to turn off the heater. If it's not working, it's likely an issue with how the data is being sent.

**Comment by importRyan** [comment]
`0000` works for my mug. Both for my [macOS app](https://github.com/importRyan/Muggle) and Ember's own app, you will see temperature continue to rise for a few seconds after shutting off the heater. 

If that's not what you observe, double-check whether you're sending a series of commands in a short amount of time.

**Comment by GiridharKarnik** [comment]
Sorry guys, my bad. I can confirm it works. Thanks for getting back.
